name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Authenticate with Firebase
      run: firebase login:ci --no-localhost --interactive

    - name: Install dependencies and build
      run: |
        npm install
        npm run build

    - name: Deploy to Firebase Hosting
      run: firebase deploy --only hosting
